image: gcc

before_script:
  - apt-get update
  - apt-get install libcmocka-dev -y

build:
  stage: build
  script:
    - make
  tags:
    - x86_64

test:
  stage: test
  script:
    - make tests -k
  tags:
    - x86_64
