#ifndef __HTTPSERV_HTTP_STATUS_H__
#define __HTTPSERV_HTTP_STATUS_H__
/*
 * Type used internally to represent statuses
 */
typedef unsigned int httpserv_http_status_t;
// 1XX
#define HTTPSERV_HTTP_STATUS_CONTINUE 100
#define HTTPSERV_HTTP_STATUS_SWITCHING_PROTOCOLS 101

// 2XX
#define HTTPSERV_HTTP_STATUS_OK 200
#define HTTPSERV_HTTP_STATUS_CREATED 201
#define HTTPSERV_HTTP_STATUS_ACCEPTED 202
#define HTTPSERV_HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION 203
#define HTTPSERV_HTTP_STATUS_NO_CONTENT 204
#define HTTPSERV_HTTP_STATUS_RESET_CONTENT 205
#define HTTPSERV_HTTP_STATUS_PARTIAL_CONTENT 206

// 3XX
#define HTTPSERV_HTTP_STATUS_MULTIPLE_CHOICES 300
#define HTTPSERV_HTTP_STATUS_MOVED_PERMANENTLY 301
#define HTTPSERV_HTTP_STATUS_FOUND 302
#define HTTPSERV_HTTP_STATUS_SEE_OTHER 303
#define HTTPSERV_HTTP_STATUS_NOT_MODIFIED 304
#define HTTPSERV_HTTP_STATUS_TEMPORARY_REDIRECT 307
#define HTTPSERV_HTTP_STATUS_PERMANENT_REDIRECT 308

// 4XX
#define HTTPSERV_HTTP_STATUS_BAD_REQUEST 400
#define HTTPSERV_HTTP_STATUS_UNAUTHORIZED 401
#define HTTPSERV_HTTP_STATUS_FORBIDDEN 403
#define HTTPSERV_HTTP_STATUS_NOT_FOUND 404
#define HTTPSERV_HTTP_STATUS_METHOD_NOT_ALLOWED 405
#define HTTPSERV_HTTP_STATUS_NOT_ACCEPTABLE 406
#define HTTPSERV_HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED 407
#define HTTPSERV_HTTP_STATUS_REQUEST_TIMEOUT 408
#define HTTPSERV_HTTP_STATUS_CONFLICT 409
#define HTTPSERV_HTTP_STATUS_GONE 410
#define HTTPSERV_HTTP_STATUS_LENGHT_REQUIRED 411
#define HTTPSERV_HTTP_STATUS_PRECONDITION_FAILED 412
#define HTTPSERV_HTTP_STATUS_PAYLOAD_TOO_LARGE 413
#define HTTPSERV_HTTP_STATUS_URI_TOO_LONG 414
#define HTTPSERV_HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE 415
#define HTTPSERV_HTTP_STATUS_RANGE_NOT_SATISFIABLE 416
#define HTTPSERV_HTTP_STATUS_EXPECTATION_FAILED 417
#define HTTPSERV_HTTP_STATUS_IM_A_TEAPOT 418
#define HTTPSERV_HTTP_STATUS_UPGRADE_REQUIRED 426
#define HTTPSERV_HTTP_STATUS_PRECONDITION_REQUIRED 428
#define HTTPSERV_HTTP_STATUS_TOO_MANY_REQUESTS 429
#define HTTPSERV_HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE 431
#define HTTPSERV_HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS 451

// 5XX
#define HTTPSERV_HTTP_STATUS_INTERNAL_SERVER_ERROR 500
#define HTTPSERV_HTTP_STATUS_NOT_IMPLEMENTED 501
#define HTTPSERV_HTTP_STATUS_BAD_GATEWAY 502
#define HTTPSERV_HTTP_STATUS_SERVICE_UNAVAILABLE 503
#define HTTPSERV_HTTP_STATUS_GATEWAY_TIMEOUT 504
#define HTTPSERV_HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED 505
#define HTTPSERV_HTTP_STATUS_VARIANT_ALSO_NEGOTIATES 506
#define HTTPSERV_HTTP_STATUS_NOT_EXTENDED 510
#define HTTPSERV_HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED 511

/*
 * This function returns the string put into responses after the status code. If
 * the status code supplied was invalid it returns NULL
 */
char *httpserv_http_strstatus(const httpserv_http_status_t status);
/*
 * This function checks wether or not status is a valid, supported status
 */
int httpserv_http_status_valid(const httpserv_http_status_t status);
#endif
